### ISSUE TITLE
Add async factories support

### ISSUE THREAD

**Issue by daniel-white** [vovaspace/brandi#13]
Would it be possible to rework things so that `container.get` returns a `Promise` and `toFactory` takes a factory that returns a `Promise` to the type?

**Comment by vovaspace** [comment]
Hi. Do you mean something like this?

```typescript
class Some {}

const TOKENS = {
  someAsyncFactory: token<Factory<Promise<Some>>>('AsyncFactory<Some>'),
};

const container = new Container();
container.bind(TOKENS.someAsyncFactory).toFactory(async () => { /* .. */ });

const someAsyncFactory = container.get(TOKENS.someAsyncFactory);
const someInstance = await someAsyncFactory();
```

Can you give an example of how you would like to use this in the context of your business logic? Thanks!

**Comment by vovaspace** [comment]
Hi @daniel-white!

I opened the [PR](https://github.com/vovaspace/brandi/pull/14) with the addition of async factories. The main changes:
- The initializer function waits for asynchronous creation of the instance;
- Factory waits for the resolution of the initialization, if the initializer has returned a `Promise`.

And it's all typed.

In your case, the logic can be implemented like this:
```typescript
import { Container, AsyncFactory, token } from 'brandi';

class BusinessLogic { /* ... */ }

const TOKENS = {
  businessLogicFactory: token<AsyncFactory<BusinessLogic>>('AsyncFactory<BusinessLogic>'),
};

const container = new Container();

container
  .bind(TOKENS.businessLogicFactory)
  /*                              ↓ Returns a Promise. */
  .toFactory(BusinessLogic, () => thirdPartyInstance.refresh());

const businessLogicFactory = container.get(TOKENS.businessLogicFactory);

/*                    ↓ Will wait for the initializer to resolve. */
const businessLogic = await businessLogicFactory();
```

Is this exactly what you need?
